site_name: Cloudron Docs
site_description: 'Cloudron is a platform to host apps on your server and keep them up-to-date and secure.'
site_url: 'https://cloudron.io'
copyright: 'Copyright &copy; 2015 - 2017 Cloudron UG'
pages:
  - 'Introduction': 'documentation.md'
  - 'Installation': 'documentation/installation.md'
  - 'Knowledge base':
    - documentation/apps.md
    - documentation/backups.md
    - documentation/certificates.md
    - documentation/domains.md
    - documentation/email.md
    - documentation/integrations.md
    - documentation/security.md
    - documentation/server.md
    - documentation/updates.md
    - 'User & Groups': documentation/user-management.md
  - 'Developer':
    - 'API': documentation/developer/api.md
    - documentation/developer/addons.md
    - documentation/developer/architecture.md
    - 'Base Image': documentation/developer/baseimage.md
    - documentation/developer/button.md
    - 'CLI': documentation/cli.md
    - documentation/developer/manifest.md
#    - documentation/developer/node.md
    - documentation/developer/packaging.md
  - 'Apps':
    - 'Confluence': documentation/apps/confluence.md
    - 'Dokuwiki': documentation/apps/dokuwiki.md
    - 'Etherpad': documentation/apps/etherpad.md
    - 'Ghost': documentation/apps/ghost.md
    - 'Gitea': documentation/apps/gitea.md
    - 'GitHub Pages': documentation/apps/githubpages.md
    - 'GitLab': documentation/apps/gitlab.md
    - 'Gogs': documentation/apps/gogs.md
    - 'Hastebin': documentation/apps/hastebin.md
    - 'Jingo': documentation/apps/jingo.md
    - 'Kanboard': documentation/apps/kanboard.md
    - 'LAMP': documentation/apps/lamp.md
    - 'Lets Chat': documentation/apps/letschat.md
    - 'Lychee': documentation/apps/lychee.md
    - 'Mailtrain': documentation/apps/mailtrain.md
    - 'Mattermost': documentation/apps/mattermost.md
    - 'Mediawiki': documentation/apps/mediawiki.md
    - 'Meemo': documentation/apps/meemo.md
    - 'Minio': documentation/apps/minio.md
    - 'Nextcloud': documentation/apps/nextcloud.md
    - 'NodeBB': documentation/apps/nodebb.md
    - 'OpenProject': documentation/apps/openproject.md
    - 'OpenVPN': documentation/apps/openvpn.md
    - 'ownCloud': documentation/apps/owncloud.md
    - 'Paperwork': documentation/apps/paperwork.md
    - 'Phabricator': documentation/apps/phabricator.md
    - 'Piwik': documentation/apps/piwik.md
    - 'Radicale': documentation/apps/radicale.md
    - 'RainLoop': documentation/apps/rainloop.md
    - 'Redash': documentation/apps/redash.md
    - 'Redmine': documentation/apps/redmine.md
    - 'Rocket.Chat': documentation/apps/rocket.chat.md
    - 'Roundcube': documentation/apps/roundcube.md
    - 'Shaarli': documentation/apps/shaarli.md
    - 'SOGo': documentation/apps/sogo.md
    - 'Surfer': documentation/apps/surfer.md
    - 'Taiga': documentation/apps/taiga.md
    - 'The Lounge': documentation/apps/thelounge.md
    - 'TinyTinyRSS': documentation/apps/tinytinyrss.md
    - 'Verdaccio': documentation/apps/verdaccio.md
    - 'Wallabag': documentation/apps/wallabag.md
    - 'Wekan': documentation/apps/wekan.md
    - 'Wordpress': documentation/apps/wordpress.md
  - 'Managed Hosting': 'documentation/managed-hosting.md'
  - 'Billing': 'documentation/billing.md'
  - 'Support': 'documentation/support.md'
extra_css:
  - 'stylesheets/extra.css'
theme:
  name: 'material'
  language: 'en'
  feature:
    tabs: false
  palette:
    primary: 'white'
    accent: 'green'
  logo: 'img/logo_small.svg'
  font:
    text: 'Noto Sans'
    code: 'Ubuntu Mono'
extra:
  search:
    tokenizer: '[\s\-]+'
  social:
    - type: 'slack'
      link: 'https://chat.cloudron.io'
    - type: 'gitlab'
      link: 'https://git.cloudron.io'
    - type: 'twitter'
      link: 'https://twitter.com/cloudron_io'
    - type: 'linkedin'
      link: 'https://linkedin.com/company/cloudron'
use_directory_urls: true
markdown_extensions:
  - admonition
  - codehilite(guess_lang=false)
  - toc(permalink=true)
  - footnotes
  - meta
