site_name: Cloudron Docs
site_description: 'Cloudron is a platform to host apps on your server and keep them up-to-date and secure.'
site_url: 'https://cloudron.io'
copyright: 'Copyright &copy; 2015 - 2017 Cloudron UG'
theme_dir: 'material/'
pages:
  - 'Introduction': 'documentation.md'
  - 'Installation': 'installation.md'
  - 'Knowledge base':
    - kb/apps.md
    - 'Backup & Restore': kb/backups.md
    - kb/certificates.md
    - 'CLI': kb/cli.md
    - kb/email.md
    - kb/integrations.md
    - kb/notifications.md
    - kb/security.md
    - kb/server.md
    - kb/updates.md
    - 'User & Groups': kb/user-management.md
  - 'Developer':
    - developer/architecture.md
    - developer/authentication.md
    - developer/addons.md
    - 'Base Image': developer/baseimage.md
    - 'API': developer/api.md
    - developer/button.md
    - developer/manifest.md
#    - developer/node.md
    - developer/packaging.md
extra_css:
  - 'stylesheets/extra.css'
extra:
  palette:
    primary: 'light blue'
    accent: 'green'
  logo: 'img/logo.svg'
  font:
    text: 'Noto Sans'
    code: 'Ubuntu Mono'
  social:
    - type: 'gitlab'
      link: 'https://git.cloudron.io'
    - type: 'twitter'
      link: 'https://twitter.com/cloudron_io'
    - type: 'linkedin'
      link: 'https://linkedin.com/company/cloudron'
site_favicon: 'img/favicon.ico'
use_directory_urls: true
markdown_extensions:
  - admonition
  - codehilite(guess_lang=false)
  - toc(permalink=true)
