site_name: Cloudron Docs
site_description: 'Cloudron is a platform to host apps on your server and keep them up-to-date and secure.'
site_url: 'https://cloudron.io'
copyright: 'Copyright &copy; 2015 - 2018 Cloudron UG'
pages:
  - 'Introduction': 'index.md'
  - 'Installation': 'installation.md'
  - 'Knowledge Base':
    - apps.md
    - 'App Store': appstore.md
    - 'Backups': backups.md
    - certificates.md
    - domains.md
    - email.md
    - integrations.md
    - security.md
    - server.md
    - updates.md
    - 'User & Groups': user-management.md
  - 'Apps':
    - 'Confluence': apps/confluence.md
    - 'Dokuwiki': apps/dokuwiki.md
    - 'Etherpad': apps/etherpad.md
    - 'Ghost': apps/ghost.md
    - 'Gitea': apps/gitea.md
    - 'GitHub Pages': apps/githubpages.md
    - 'GitLab': apps/gitlab.md
    - 'Gogs': apps/gogs.md
    - 'Hastebin': apps/hastebin.md
    - 'Invoice Ninja': apps/invoiceninja.md
    - 'Jingo': apps/jingo.md
    - 'Kanboard': apps/kanboard.md
    - 'LAMP': apps/lamp.md
    - 'Lets Chat': apps/letschat.md
    - 'Lychee': apps/lychee.md
    - 'Mailtrain': apps/mailtrain.md
    - 'Mattermost': apps/mattermost.md
    - 'Mediawiki': apps/mediawiki.md
    - 'Meemo': apps/meemo.md
    - 'Minio': apps/minio.md
    - 'Nextcloud': apps/nextcloud.md
    - 'NodeBB': apps/nodebb.md
    - 'OpenProject': apps/openproject.md
    - 'OpenVPN': apps/openvpn.md
    - 'ownCloud': apps/owncloud.md
    - 'Paperwork': apps/paperwork.md
    - 'Phabricator': apps/phabricator.md
    - 'Piwik': apps/piwik.md
    - 'Radicale': apps/radicale.md
    - 'RainLoop': apps/rainloop.md
    - 'Redash': apps/redash.md
    - 'Redmine': apps/redmine.md
    - 'Rocket.Chat': apps/rocket.chat.md
    - 'Roundcube': apps/roundcube.md
    - 'Shaarli': apps/shaarli.md
    - 'SOGo': apps/sogo.md
    - 'Surfer': apps/surfer.md
    - 'Syncthing': apps/syncthing.md
    - 'Taiga': apps/taiga.md
    - 'The Lounge': apps/thelounge.md
    - 'TinyTinyRSS': apps/tinytinyrss.md
    - 'Verdaccio': apps/verdaccio.md
    - 'Wallabag': apps/wallabag.md
    - 'Wekan': apps/wekan.md
    - 'Wordpress': apps/wordpress.md
  - 'Managed Hosting': 'managed-hosting.md'
  - 'Billing': 'billing.md'
  - 'Support': 'support.md'
extra_css:
  - 'stylesheets/extra.css'
theme:
  name: 'material'
  language: 'en'
  feature:
    tabs: false
  palette:
    primary: 'white'
    accent: 'green'
  logo: 'img/logo_small.svg'
  favicon: 'img/favicon.ico'
  font:
    text: 'Noto Sans'
    code: 'Ubuntu Mono'
extra:
  search:
    tokenizer: '[\s\-]+'
  social:
    - type: 'slack'
      link: 'https://chat.cloudron.io'
    - type: 'gitlab'
      link: 'https://git.cloudron.io'
    - type: 'twitter'
      link: 'https://twitter.com/cloudron_io'
    - type: 'linkedin'
      link: 'https://linkedin.com/company/cloudron'
    - type: 'comments'
      link: 'https://forum.cloudron.io'
use_directory_urls: true
markdown_extensions:
  - admonition
  - codehilite(guess_lang=false)
  - toc(permalink=true)
  - footnotes
  - meta
